import { Customer, ICustomer } from '../models/Customer.model';
import { Partner, IPartner } from '../models/Partner.model';
import { ValidationError } from '../utils/AppError';

export class RegistrationService {
  /**
   * Register a new customer
   */
  async registerCustomer(data: {
    companyName: string;
    email: string;
    address: string;
  }): Promise<ICustomer> {
    // Check if customer already exists
    const existingCustomer = await Customer.findOne({
      $or: [{ email: data.email }, { companyName: data.companyName }],
    });

    if (existingCustomer) {
      if (existingCustomer.email === data.email) {
        throw new ValidationError('Customer with this email already exists');
      }
      throw new ValidationError('Customer with this company name already exists');
    }

    // Create new customer
    const customer = await Customer.create(data);
    return customer;
  }

  /**
   * Register a new partner with auto-generated API keys
   */
  async registerPartner(data: {
    companyName: string;
    email: string;
    documentTypesConfig: string[];
  }): Promise<{ partner: IPartner; apiKey: string; apiSecret: string }> {
    // Check if partner already exists
    const existingPartner = await Partner.findOne({
      $or: [{ email: data.email }, { companyName: data.companyName }],
    });

    if (existingPartner) {
      if (existingPartner.email === data.email) {
        throw new ValidationError('Partner with this email already exists');
      }
      throw new ValidationError('Partner with this company name already exists');
    }

    // Create new partner (apiKey and apiSecret will be auto-generated by pre-save hook)
    const partner = await Partner.create(data);

    // Fetch the partner with apiSecret (since it's not selected by default)
    const partnerWithSecret = await Partner.findById(partner._id).select('+apiSecret');

    if (!partnerWithSecret) {
      throw new Error('Failed to retrieve partner after creation');
    }

    return {
      partner: partner,
      apiKey: partnerWithSecret.apiKey,
      apiSecret: partnerWithSecret.apiSecret,
    };
  }
}

export const registrationService = new RegistrationService();
